# Generated by Django 5.2.3 on 2026-05-16 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('HEALTH', 'Health'), ('POLICE', 'Police'), ('FIRE', 'Fire'), ('PANCHAYAT', 'Panchayat'), ('TRANSPORT', 'Transport'), ('WOMEN_CHILD', 'Women & child help'), ('DISASTER', 'Disaster response')], max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('secondary_phone', models.CharField(blank=True, max_length=15)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('notes', models.CharField(blank=True, max_length=220)),
                ('available_24x7', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LocalUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('ANNOUNCEMENT', 'Local announcement'), ('BUS', 'Bus & transport'), ('TEMPLE', 'Temple & festival'), ('HEALTH', 'Health camp'), ('FARMER', 'Farmer update'), ('SCHOOL', 'School & college'), ('PANCHAYAT', 'Panchayat notice'), ('JOB', 'Local job'), ('MARKET', 'Buy & sell'), ('WEATHER', 'Rain & weather')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=120)),
                ('contact_name', models.CharField(blank=True, max_length=80)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('event_datetime', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_local_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_urgent', '-is_pinned', 'event_datetime', '-created_at'],
            },
        ),
    ]
