# Generated by Django 5.2.3 on 2026-05-16 16:45

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_daily_hub'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringLocalUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('ANNOUNCEMENT', 'Local announcement'), ('BUS', 'Bus & transport'), ('TEMPLE', 'Temple & festival'), ('HEALTH', 'Health camp'), ('FARMER', 'Farmer update'), ('SCHOOL', 'School & college'), ('PANCHAYAT', 'Panchayat notice'), ('JOB', 'Local job'), ('MARKET', 'Buy & sell'), ('WEATHER', 'Rain & weather')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=120)),
                ('contact_name', models.CharField(blank=True, max_length=80)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=20)),
                ('days_of_week', models.CharField(blank=True, help_text='For weekly rules: comma-separated weekdays, Monday=0 ... Sunday=6.', max_length=20)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('publish_time', models.TimeField(default=datetime.time(6, 0))),
                ('valid_days', models.PositiveSmallIntegerField(default=1)),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_generated_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.AddField(
            model_name='localupdate',
            name='generated_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localupdate',
            name='generated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_updates', to='core.recurringlocalupdate'),
        ),
    ]
