# Generated by Django 5.2.3 on 2026-08-16 07:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import editor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('prompt', models.TextField(blank=True)),
                ('target_duration', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(180)])),
                ('canvas_width', models.PositiveSmallIntegerField(default=1080)),
                ('canvas_height', models.PositiveSmallIntegerField(default=1920)),
                ('template_source', models.CharField(choices=[('NONE', 'None'), ('VN_QR', 'VN QR'), ('VN_FILE', 'VN template file'), ('MANUAL', 'Manual')], default='NONE', max_length=20)),
                ('template_payload', models.TextField(blank=True)),
                ('template_notes', models.TextField(blank=True)),
                ('timeline', models.JSONField(blank=True, default=editor.models.default_timeline)),
                ('render_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PLANNED', 'Plan ready'), ('RENDERING', 'Rendering'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('render_message', models.TextField(blank=True)),
                ('output_video', models.FileField(blank=True, upload_to=editor.models.editor_render_upload_path)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditorAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('VIDEO', 'Video'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('QR', 'QR code'), ('TEMPLATE', 'Template'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to=editor.models.editor_asset_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='editor.editorproject')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
