# Generated by Django 5.2.3 on 2025-07-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('AUTO', 'Auto Driver'), ('PLUMBER', 'Plumber'), ('ELECTRICIAN', 'Electrician'), ('BARBER', 'Barber')], max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
