# Generated by Django 5.2.3 on 2025-07-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_booking_created_at_booking_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_datetime',
            field=models.DateTimeField(default='2025-07-20 10:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, default='2025-07-20 10:00:00'),
            preserve_default=False,
        ),
    ]
