# Generated by Django 5.2.3 on 2026-05-09 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(help_text='FontAwesome icon class, e.g. fa-solid fa-graduation-cap', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='places/')),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('reviews_count', models.IntegerField(default=0)),
                ('map_url', models.URLField(blank=True, help_text='Google Maps URL', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='locations.category')),
            ],
        ),
    ]
